# VSCode settings for markdownlint
# "markdownlint.config": {
#     "siblings_only": true,
#     "ul-indent": false,        
#     "no-inline-html": false
# }

# This environment file is for the NAATOS project, which uses mkdocs and various plugins.
name: NAATOS
channels:
  - conda-forge
dependencies:
  - pip=25.0.1=pyh8b19718_0
  - python=3.12.10=h3f84c4b_0_cpython
  - pip:
      - mkdocs==1.6.1
      - mkdocs-awesome-nav==3.1.1
      - mkdocs-macros-plugin==1.3.7
      - mkdocs-material==9.6.12
      - mkdocs-material-extensions==1.3.1
      - mkdocs-table-reader-plugin==3.1.0
      - pandas==2.2.3
